all:
	g++ conv.cpp -O3 -lpthread -o conv.out
	g++ conv_sk.cpp -O3 -lpthread -o conv_sk.out
	g++ conv_tp.cpp -O3 -lpthread -o conv_tp.out
	g++ conv_tprow.cpp -O3 -lpthread -o conv_tprow.out

clean:
	rm -rf *.out